### PR TITLE
add range and log options

### PR DESCRIPTION
**Pull request by FokkeZB**
Get contributors without merges for a specific release:

```
git-contributors . --range 5_0_1_GA..5_0_2_GA --log "--no-merges"
```

### CODE REVIEW

**Comment by nathanbrauer** [comment]
:+1:

**Comment by FokkeZB** [comment]
Closing for inactivity

**Comment by FokkeZB** [comment]
@davidlinse I noticed you've reopened it, but any chance this is going to be merged? Otherwise I'd say we close it and clean up my GitHub activity :P

**Comment by FokkeZB** [comment]
Closing for inactivity.

**Pull request closed without merging**
